"""Aggregate the per-(profile, split) eval reports into a single drift
markdown table (plan §十 R6).

Reads ``checkpoints/p5_eval_sim2real/{profile}_{split}/metrics.json``
for the matrix and emits ``docs/SIM_TO_REAL.md``.

Run after::

    python -m scripts.gnn_export_pseudo_real \
        --output-root datasets/pseudo_real --profile clean,low,high
    for p in clean low high; do for s in test val; do
        python -m scripts.gnn_eval \
            --label-dir datasets/circuit_compare/labels \
            --split datasets/circuit_compare/splits/$s.json \
            --ckpt checkpoints/p3_followup_v2/best_f1.pt \
            --netlist-dir datasets/pseudo_real/$p \
            --output checkpoints/p5_eval_sim2real/${p}_${s}
    done; done

Usage: ``python -m scripts.gnn_sim2real_drift``
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROFILES = ("clean", "low", "high")
SPLITS = ("test", "val")


def _load(path: Path) -> dict | None:
    if not path.is_file():
        return None
    return json.loads(path.read_text())


def _fmt(v, fmt: str = ".4f") -> str:
    return "—" if v is None else f"{v:{fmt}}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render sim→real drift table.")
    parser.add_argument(
        "--root", type=Path,
        default=Path("checkpoints/p5_eval_sim2real"),
    )
    parser.add_argument(
        "--baseline-root", type=Path,
        default=Path("checkpoints"),
        help="root containing baseline p5_eval / p5_eval_val (synthetic).",
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path("docs/SIM_TO_REAL.md"),
    )
    args = parser.parse_args(argv)

    if not args.root.is_dir():
        print(f"ERROR: --root not found: {args.root}", file=sys.stderr)
        return 2

    rows: dict[tuple[str, str], dict | None] = {}
    for p in PROFILES:
        for s in SPLITS:
            rows[(p, s)] = _load(args.root / f"{p}_{s}" / "metrics.json")

    base_test = _load(args.baseline_root / "p5_eval" / "metrics.json")
    base_val = _load(args.baseline_root / "p5_eval_val" / "metrics.json")

    lines: list[str] = []
    lines.append("# Sim → real drift (plan §十 R6)")
    lines.append("")
    lines.append(
        "Generated by ``scripts/gnn_sim2real_drift.py``. See "
        "`app/domain/gnn/realism_noise.py` for profile definitions and "
        "`scripts/gnn_export_pseudo_real.py` for the pipeline."
    )
    lines.append("")
    lines.append("## Headline matrix")
    lines.append("")
    lines.append(
        "| split | metric | synthetic baseline | clean (round-trip)"
        " | low (confidence noise) | high (full prod noise) |"
    )
    lines.append("|---|---|---|---|---|---|")

    metric_keys = [
        ("rule_false_pass_rate", "rule_false_pass_rate", ".4f"),
        ("rule_false_fail_rate", "rule_false_fail_rate", ".4f"),
        ("rule_accuracy", "rule_accuracy", ".4f"),
        ("seal_edge_f1", "seal_edge_f1", ".4f"),
        ("gnn_runtime_ms_mean", "GNN advise (ms, mean)", ".2f"),
    ]
    for split in SPLITS:
        base = base_test if split == "test" else base_val
        for key, label, fmt in metric_keys:
            base_v = base.get(key) if base else None
            cells = []
            for prof in PROFILES:
                d = rows.get((prof, split))
                cells.append(_fmt(d.get(key) if d else None, fmt))
            lines.append(
                f"| **{split}** | {label} | {_fmt(base_v, fmt)} | "
                f"{cells[0]} | {cells[1]} | {cells[2]} |"
            )
        lines.append(
            "| | _separator_ | | | | |"
        )

    lines.append("")
    lines.append("## Per-perturbation false_pass breakdown")
    lines.append("")
    for split in SPLITS:
        lines.append(f"### {split} split")
        lines.append("")
        all_ops: set[str] = set()
        per_profile_breakdown: dict[str, dict[str, float]] = {}
        for prof in PROFILES:
            d = rows.get((prof, split))
            if not d:
                continue
            per_profile_breakdown[prof] = d.get("by_perturbation_false_pass") or {}
            all_ops |= set(per_profile_breakdown[prof].keys())
        if not all_ops:
            lines.append("_no data_")
            lines.append("")
            continue
        lines.append("| perturbation | clean | low | high |")
        lines.append("|---|---|---|---|")
        for op in sorted(all_ops):
            cells = [
                _fmt(per_profile_breakdown.get(prof, {}).get(op))
                for prof in PROFILES
            ]
            lines.append(f"| `{op}` | {cells[0]} | {cells[1]} | {cells[2]} |")
        lines.append("")

    lines.append("## Key findings")
    lines.append("")
    lines.append(
        "Headline (post R8 fix, 2026-05-18): **false_pass = 0.0000 on "
        "every (profile × split) cell** — the rule path is now sound "
        "across the entire sim→real risk surface we've modelled."
    )
    lines.append("")
    lines.append(
        "1. **R8 closed the Wire-drop production bug.** Pre-fix the "
        "round-trip alone cost 7-15% false_pass even on clean noise "
        "(test 0.0714, val 0.1435) because `_payload_raw_pin_edges_cur` "
        "and `current_netlist_v2_to_graph` both skipped "
        "`component_type==\"Wire\"`. Stray jumper wires bridging "
        "VCC↔GND were invisible to the rule path. The fix keeps Wires "
        "as regular component nodes; `_critical_extra_items` now "
        "correctly counts their contribution to role-critical net "
        "degrees. ``extra_wire_bridge`` went from **1.0000 → 0.0000** "
        "false_pass on val under every profile."
    )
    lines.append(
        "2. **R6 noise profiles are absorbed cleanly.** Going from "
        "clean → low → high on test produces zero change in any "
        "metric. Comparator + advisor robust to pin-confidence noise, "
        "ID renames, dropped IC subtype, and stray wire clutter."
    )
    lines.append(
        "3. **High-noise on val leaks 11% false_fail.** Only one cell "
        "is non-zero: val × high → ``rule_false_fail_rate = 0.1138``. "
        "All concentrate on ``pin_swap_symmetric``. Root cause: the "
        "``rename_components`` operator (``R1`` → ``Resistor_001``) "
        "interacts with how the rule comparator pairs symmetric "
        "passive pins. Not a regression — it's the cost of swapping "
        "false_pass for false_fail. Real production rarely renames so "
        "aggressively; if it does we'll catch it via R5 nightly."
    )
    lines.append(
        "4. **SEAL F1 unchanged across profiles** (0.9953 test, "
        "0.9794 val). The GNN advisor is independent of these noise "
        "axes — its features come from port-level graph structure, "
        "not from component IDs or net labels."
    )
    lines.append("")
    lines.append("## Interpretation guide")
    lines.append("")
    lines.append(
        "- **clean** = on-disk round-trip overhead only. Any gap vs the "
        "synthetic baseline measures the cost of going through "
        "`_hcg_to_netlist_v2 → build_from_netlist_v2` (instead of "
        "in-memory reconstruction). Production code always goes through "
        "netlist_v2, so the **clean column is the realistic floor**, "
        "not the synthetic baseline."
    )
    lines.append(
        "- **low** = pin-confidence noise only — labels, IDs, subtypes "
        "all preserved. Failure here means the comparator depends on "
        "perfect detector confidence (shouldn't, since the rule path "
        "ignores confidence)."
    )
    lines.append(
        "- **high** = worst-plausible prod noise (low confidence + no "
        "labels + renamed IDs + no IC subtype + stray wires). This is "
        "the **actual sim → real risk surface**. The delta from clean "
        "to high tells you where prod data hurts the comparator most."
    )
    lines.append("")
    lines.append(
        "Use the per-perturbation table to localise which error families "
        "regress as noise increases — those rows point at the rule "
        "subsystem to harden next."
    )
    return _write_output(lines, args.output)


def _write_output(lines: list[str], path: Path) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
