"""Build-time PDF -> DatasheetDocument JSON ingest pipeline.

This script is intentionally **not** part of the LabGuardian runtime. It runs
on a developer / CI machine, parses one or more datasheet PDFs, and writes
``DatasheetDocument`` JSON files into ``knowledge/datasheets/``. The board
afterwards only consumes the produced JSON + assets — it never imports MinerU,
Magic-PDF, or any layout/OCR model.

Three backends, in priority order:

1. ``mineru`` — full multimodal parse (text / table / figure / formula /
   layout). Requires ``pip install '.[ingest]'``; pulls model weights on first
   run. Produces the richest output.
2. ``magic_pdf`` — same project, older package name. Compatible adapter kept
   here so older environments still work.
3. ``pypdf`` — text-only fallback that ships in the runtime deps. No external
   downloads, no GPU. Used today when MinerU isn't installed; produces real
   per-page text chunks but cannot extract figures / tables.

Merge semantics:

- If the target JSON already exists, the script preserves manually authored
  figure / table / schematic / waveform chunks and replaces only text chunks
  with newly extracted content. Document-level metadata (title, part_numbers,
  source_path) is taken from the existing JSON if present, else from CLI args.
- ``--overwrite`` discards the existing file entirely.

CLI examples
============

::

    python scripts/ingest_datasheets.py \
        --pdf knowledge_base/C695838_555定时器-计时器_NE555DR_规格书_WJ1799212.PDF \
        --document-id ne555 \
        --out knowledge/datasheets/ne555.json

    python scripts/ingest_datasheets.py \
        --pdf knowledge_base/sn74ls74a.pdf \
        --document-id sn74ls74a \
        --title "SN74LS74A 双 D 触发器" \
        --part-numbers SN74LS74A SN74LS74AN \
        --out knowledge/datasheets/sn74ls74a.json \
        --backend pypdf
"""

from __future__ import annotations

import argparse
import importlib
import json
import logging
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from app.schemas.kb import DatasheetChunk, DatasheetDocument  # noqa: E402

logger = logging.getLogger("ingest_datasheets")

# Token regex matches CJK characters individually and Latin/digit runs together.
_TOKEN_PATTERN = re.compile(r"[A-Za-z0-9]+|[一-鿿]")
_STOPWORDS = {
    "的", "是", "在", "和", "或", "与", "及", "为", "了", "也", "可", "见", "如",
    "the", "and", "or", "of", "to", "for", "in", "on", "with", "by", "is", "are",
    "this", "that", "be", "as", "an", "a", "at", "from",
}


def _tokenize(text: str) -> list[str]:
    return [tok.lower() for tok in _TOKEN_PATTERN.findall(text or "")]


def _top_keywords(text: str, limit: int = 8) -> list[str]:
    counts = Counter(
        tok
        for tok in _tokenize(text)
        if len(tok) > 1 and tok not in _STOPWORDS
    )
    return [tok for tok, _ in counts.most_common(limit)]


# ---------------------------------------------------------------------------
# Backends
# ---------------------------------------------------------------------------


class IngestBackend:
    name: str = ""

    def is_available(self) -> bool:
        raise NotImplementedError

    def parse(self, pdf_path: Path, document_id: str, asset_dir: Path) -> list[DatasheetChunk]:
        raise NotImplementedError


class PypdfBackend(IngestBackend):
    """Text-only per-page chunking with the pypdf library.

    Produces one ``text`` chunk per page. Snippet, page number and keyword
    list come straight from the page text. Cannot extract figures or tables —
    those must be authored manually or generated by MinerU.
    """

    name = "pypdf"

    def is_available(self) -> bool:
        try:
            importlib.import_module("pypdf")
            return True
        except Exception:
            return False

    def parse(self, pdf_path: Path, document_id: str, asset_dir: Path) -> list[DatasheetChunk]:
        from pypdf import PdfReader

        reader = PdfReader(str(pdf_path))
        chunks: list[DatasheetChunk] = []
        garbage_pages = 0
        for index, page in enumerate(reader.pages, start=1):
            try:
                text = page.extract_text() or ""
            except Exception as exc:  # noqa: BLE001
                logger.warning("page %s extract failed: %s", index, exc)
                continue
            normalized = _normalize_whitespace(text)
            if not normalized:
                continue
            if _is_font_glyph_garbage(normalized):
                # PDFs encoded with subset CIDs (no ToUnicode CMap) come back
                # as `/C0083/C0078/...` glyph IDs that pypdf can't decode. We
                # refuse to ship these as "chunks" — the next backend (MinerU
                # / OCR) is the real fix. Surface a clear error instead.
                garbage_pages += 1
                continue
            title = _first_line(normalized) or f"{document_id} p{index}"
            chunk = DatasheetChunk(
                chunk_id=f"{document_id}.p{index:03d}.text",
                modality="text",
                title=title[:80],
                text=normalized,
                page=index,
                section=None,
                keywords=_top_keywords(normalized),
                source_ref={"page": index, "backend": self.name},
            )
            chunks.append(chunk)

        if not chunks and garbage_pages:
            raise RuntimeError(
                f"pypdf produced only glyph-encoded output for {pdf_path.name} "
                f"({garbage_pages} pages of `/Cnnnn` IDs). This PDF needs an OCR "
                "or font-aware backend — re-run with `--backend mineru` after "
                "`pip install '.[ingest]'`."
            )
        return chunks


def _is_font_glyph_garbage(text: str) -> bool:
    """Detect pypdf output that's actually CID/glyph IDs, not human text.

    Symptom: many tokens of the form ``/C0083/C0078/...``. We require >40% of
    the characters to look like that pattern before declaring the page dead.
    """
    if "/C0" not in text:
        return False
    total = max(1, len(text))
    hits = sum(len(m) for m in re.findall(r"(?:/C\d{4})+", text))
    return hits / total > 0.4


class MineruBackend(IngestBackend):
    """Adapter for the MinerU multimodal parser.

    Real implementation; lazily imports ``mineru``. When MinerU isn't
    installed, ``is_available`` returns False and the script falls back to
    the next backend. The output is normalized into our DatasheetChunk schema
    so downstream code is backend-agnostic.
    """

    name = "mineru"
    _module_candidates = ("mineru", "mineru.cli", "magic_pdf")

    def is_available(self) -> bool:
        for name in self._module_candidates:
            try:
                importlib.import_module(name)
                return True
            except Exception:
                continue
        return False

    def parse(self, pdf_path: Path, document_id: str, asset_dir: Path) -> list[DatasheetChunk]:
        # The MinerU public API has shifted across releases (magic_pdf →
        # mineru). We resolve at runtime and convert whichever shape we get
        # into DatasheetChunk objects. This keeps the script honest: when you
        # `pip install '.[ingest]'` and re-run, it produces real multimodal
        # chunks; otherwise the ImportError is surfaced and you fall through.
        try:
            from mineru.api import pipeline  # type: ignore[import-not-found]
        except Exception:
            try:
                from magic_pdf.pipe.UNIPipe import UNIPipe  # type: ignore[import-not-found]
                from magic_pdf.rw.DiskReaderWriter import DiskReaderWriter  # type: ignore[import-not-found]
            except Exception as exc:  # noqa: BLE001
                raise RuntimeError(
                    "MinerU / Magic-PDF API not importable. Install with "
                    "`pip install '.[ingest]'` or pick --backend pypdf."
                ) from exc
            return list(self._parse_with_magic_pdf(pdf_path, document_id, asset_dir, UNIPipe, DiskReaderWriter))

        asset_dir.mkdir(parents=True, exist_ok=True)
        pages = pipeline.parse(str(pdf_path))  # type: ignore[attr-defined]
        return list(_chunks_from_mineru_pages(pages, document_id, asset_dir))

    def _parse_with_magic_pdf(
        self,
        pdf_path: Path,
        document_id: str,
        asset_dir: Path,
        UNIPipe: Any,
        DiskReaderWriter: Any,
    ) -> Iterable[DatasheetChunk]:
        asset_dir.mkdir(parents=True, exist_ok=True)
        writer = DiskReaderWriter(str(asset_dir))
        pipe = UNIPipe(str(pdf_path), {"_pdf_type": "txt", "model_list": []}, writer)
        pipe.pipe_classify()
        pipe.pipe_analyze()
        pipe.pipe_parse()
        result = pipe.pipe_mk_uni_format(str(asset_dir), drop_mode="none")
        yield from _chunks_from_magic_pdf_result(result, document_id, asset_dir)


def _chunks_from_mineru_pages(
    pages: Iterable[Any],
    document_id: str,
    asset_dir: Path,
) -> Iterable[DatasheetChunk]:
    counter = 0
    for page_data in pages:
        page_no = getattr(page_data, "page_no", None) or getattr(page_data, "page", None)
        blocks = getattr(page_data, "blocks", None) or []
        for block in blocks:
            counter += 1
            modality = _coerce_modality(getattr(block, "type", "text"))
            text = getattr(block, "text", None) or getattr(block, "content", None) or ""
            normalized = _normalize_whitespace(str(text))
            chunk_id = f"{document_id}.p{int(page_no or 0):03d}.{modality}.{counter}"
            asset_path: str | None = None
            table_html: str | None = None
            if modality == "table":
                table_html = getattr(block, "html", None)
            if modality in {"figure", "schematic", "waveform"}:
                rel = getattr(block, "image_path", None)
                if rel:
                    asset_path = str((asset_dir / Path(rel).name).relative_to(REPO_ROOT))
            yield DatasheetChunk(
                chunk_id=chunk_id,
                modality=modality,
                title=_first_line(normalized) or f"{document_id} block {counter}",
                text=normalized or None,
                page=int(page_no) if page_no else None,
                section=getattr(block, "section", None),
                keywords=_top_keywords(normalized),
                asset_path=asset_path,
                table_html=table_html,
                source_ref={"page": page_no, "backend": "mineru"},
            )


def _chunks_from_magic_pdf_result(
    result: Any,
    document_id: str,
    asset_dir: Path,
) -> Iterable[DatasheetChunk]:
    pdf_info = result.get("pdf_info") if isinstance(result, dict) else None
    if not pdf_info:
        return
    for page in pdf_info:
        page_no = page.get("page_idx", 0) + 1
        for index, block in enumerate(page.get("preproc_blocks", []), start=1):
            modality = _coerce_modality(block.get("type", "text"))
            text = _normalize_whitespace(str(block.get("text", "")))
            asset_path = None
            if modality in {"figure", "schematic", "waveform"} and block.get("img_path"):
                asset_path = str((asset_dir / Path(block["img_path"]).name).relative_to(REPO_ROOT))
            yield DatasheetChunk(
                chunk_id=f"{document_id}.p{page_no:03d}.{modality}.{index}",
                modality=modality,
                title=_first_line(text) or f"{document_id} p{page_no} {modality}",
                text=text or None,
                page=page_no,
                section=block.get("section"),
                keywords=_top_keywords(text),
                asset_path=asset_path,
                table_html=block.get("html"),
                source_ref={"page": page_no, "backend": "magic_pdf"},
            )


_MODALITY_MAP = {
    "title": "text",
    "text": "text",
    "table": "table",
    "image": "figure",
    "figure": "figure",
    "schematic": "schematic",
    "waveform": "waveform",
    "formula": "text",
}


def _coerce_modality(raw: str) -> str:
    return _MODALITY_MAP.get(str(raw or "").lower(), "text")


def _normalize_whitespace(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def _first_line(text: str) -> str:
    if not text:
        return ""
    candidates = [seg.strip() for seg in re.split(r"[。\.\n]", text) if seg.strip()]
    return candidates[0] if candidates else ""


# ---------------------------------------------------------------------------
# Backend resolution + merge
# ---------------------------------------------------------------------------


_BACKEND_REGISTRY: dict[str, type[IngestBackend]] = {
    "mineru": MineruBackend,
    "magic_pdf": MineruBackend,
    "pypdf": PypdfBackend,
}


def resolve_backend(name: str) -> IngestBackend:
    if name == "auto":
        # Priority order matches the module docstring.
        for candidate in (MineruBackend, PypdfBackend):
            backend = candidate()
            if backend.is_available():
                return backend
        raise RuntimeError("no ingest backend available. Try `--backend pypdf`.")
    cls = _BACKEND_REGISTRY.get(name)
    if cls is None:
        raise SystemExit(f"unknown backend: {name}")
    backend = cls()
    if not backend.is_available():
        raise SystemExit(
            f"backend `{name}` not available — required modules not importable. "
            f"Install with `pip install '.[ingest]'` or pick another backend."
        )
    return backend


def merge_document(
    existing: DatasheetDocument | None,
    *,
    document_id: str,
    title: str,
    part_numbers: list[str],
    source_path: str,
    new_chunks: list[DatasheetChunk],
    overwrite: bool,
) -> DatasheetDocument:
    """Phase 2 merge rules.

    - text-modality chunks: replaced by ``new_chunks`` (which today come from
      pypdf, tomorrow from MinerU).
    - non-text chunks (figure / table / schematic / waveform): preserved from
      the existing JSON so hand-authored Phase 1 placeholders survive until
      MinerU re-runs and supersedes them.
    - document-level fields prefer the CLI args when provided, else fall back
      to the existing JSON.
    """
    if overwrite or existing is None:
        return DatasheetDocument(
            document_id=document_id,
            title=title or document_id,
            part_numbers=part_numbers,
            source_path=source_path,
            chunks=new_chunks,
        )

    preserved = [c for c in existing.chunks if c.modality != "text"]
    return DatasheetDocument(
        document_id=existing.document_id,
        title=title or existing.title or document_id,
        part_numbers=part_numbers or existing.part_numbers,
        source_path=source_path or existing.source_path or "",
        chunks=preserved + new_chunks,
    )


def load_existing(path: Path) -> DatasheetDocument | None:
    if not path.exists():
        return None
    try:
        return DatasheetDocument.model_validate(json.loads(path.read_text(encoding="utf-8")))
    except Exception as exc:  # noqa: BLE001
        logger.warning("existing JSON unreadable, will overwrite: %s", exc)
        return None


def write_document(path: Path, document: DatasheetDocument) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = document.model_dump(exclude_none=False)
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--pdf", required=True, type=Path, help="path to the source PDF")
    parser.add_argument("--document-id", required=True, help="stable document id (becomes chunk_id prefix)")
    parser.add_argument("--out", required=True, type=Path, help="output DatasheetDocument JSON path")
    parser.add_argument("--title", default="", help="document title; falls back to existing JSON or document_id")
    parser.add_argument(
        "--part-numbers",
        nargs="*",
        default=[],
        help="part numbers / aliases for keyword expansion",
    )
    parser.add_argument(
        "--backend",
        default="auto",
        choices=["auto", "mineru", "magic_pdf", "pypdf"],
        help="parse backend (auto picks the best available)",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="discard existing JSON entirely instead of merging",
    )
    parser.add_argument("--verbose", "-v", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_arg_parser().parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s %(name)s: %(message)s",
    )

    pdf_path: Path = args.pdf.resolve()
    if not pdf_path.exists():
        logger.error("pdf not found: %s", pdf_path)
        return 2

    backend = resolve_backend(args.backend)
    logger.info("using backend=%s for %s", backend.name, pdf_path.name)

    out_path: Path = args.out.resolve()
    asset_dir = out_path.parent / "assets" / args.document_id
    new_chunks = backend.parse(pdf_path, args.document_id, asset_dir)
    logger.info("backend produced %d chunks", len(new_chunks))

    existing = load_existing(out_path)
    try:
        source_path = str(pdf_path.relative_to(REPO_ROOT))
    except ValueError:
        source_path = str(pdf_path)

    document = merge_document(
        existing,
        document_id=args.document_id,
        title=args.title,
        part_numbers=list(args.part_numbers),
        source_path=source_path,
        new_chunks=new_chunks,
        overwrite=args.overwrite,
    )

    write_document(out_path, document)
    logger.info(
        "wrote %s — %d total chunks (modalities: %s)",
        out_path.relative_to(REPO_ROOT) if out_path.is_relative_to(REPO_ROOT) else out_path,
        len(document.chunks),
        ",".join(sorted({c.modality for c in document.chunks})),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
